import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  #"~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  #"~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 11.25

#[font.offset]
#x = 1
#y = 1

[font.normal]
family = "RobotoMono Nerd Font Mono"
style = "Regular"

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
  #{ key = "Left",     mods = "Alt",     chars = "\u001bb"                         }, # Skip word left
  #{ key = "Right",    mods = "Alt",     chars = "\u001bf"                         }, # Skip word right
  #{ key = "Back",     mods = "Alt",     chars = "\u001b\u007f"                    } # Delete word
  #{ key = "Left",     mods = "Command", chars = "\u001bOH",   mode = "AppCursor"  }, # Home
  #{ key = "Right",    mods = "Command", chars = "\u001bOF",   mode = "AppCursor"  }, # End
  #{ key = "Back",     mods = "Command", chars = "\u0015"                          }, # Delete line
  #{ key = "Back",     chars = "\u0015"                                            }, # Delete word
]
