require'nvim-treesitter.configs'.setup {
  -- A list of parser names, or "all"
  ensure_installed = {
    "asm",
    "bash",
    "c",
    "c_sharp",
    "cmake",
    "comment",
    "cpp",
    "css",
    "csv",
    "cuda",
    "dockerfile",
    "gdscript",
    "go",
    "gomod",
    "graphql",
    "helm",
    "html",
    "html",
    "ini",
    "java",
    "javascript",
    "jsdoc",
    "json",
    "kotlin",
    "lua",
    "make",
    "powershell",
    "python",
    "regex",
    "ruby",
    "rust",
    "scss",
    "sql",
    "terraform",
    "tmux",
    "toml",
    "tsv",
    "tsx",
    "typescript",
    "vim",
    "xml",
    "yaml",
  },

  -- Install parsers synchronously (only applied to `ensure_installed`)
  sync_install = false,
  auto_install = true,
  highlight = {
    enable = true,
  },
  indent = {
    enable = true,
  },
}

